pub mod dashboard;
pub mod configuration;
pub mod action_rename_database;
pub mod action_rename_partner;
pub mod action_change_theme_color;
pub mod action_change_ausgeschlossene_kategorien;
pub mod change_config;
pub mod action_change_farben;
pub mod action_rename_kategorie;