
dist: focal
language: python
python:
  - "3.9"
php:
  - 7.4
sudo: required

install: 
  - sh ci/install_requirements.sh

env:
  global:
  - TRAVIS_INTEGRATION=TRUE

addons:
  sonarcloud:
    organization: "sebastianrzk-github"
  firefox: "61.0"
  chrome: stable

services:
  - mysql

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.21.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - mysql -e 'CREATE DATABASE testdb;'
  - wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh
  - source ~/.nvm/nvm.sh
  - nvm install 12

jobs:
  include:
    - stage: butler_offline::unit_test
      script: sh ci/run_unit_tests.sh
    - stage: butler_offline::selenium_test
      script: sh ci/run_integration_tests.sh
    - stage: butler_online
      script: sh ci/online.sh
    - stage: notify_ci_services
      script: sh ci/notify_integration_services.sh


