# Stage 1
FROM node:14-slim as build-step-angular
RUN mkdir -p /app
WORKDIR /app
COPY butler_online/budgetbutler/package.json /app
RUN npm install
COPY butler_online/budgetbutler /app
RUN npm run build --prod
RUN ls -la /app/dist


FROM sebastianrzk/docker-chromium-xvfb as build-step-angular-test
WORKDIR /usr/src/app
RUN apt-get update
RUN apt-get install -y gpg \
    && curl -sL https://deb.nodesource.com/setup_14.x | bash - \
    && apt-get install -y nodejs gpg \
    && rm -rf /var/lib/apt/lists
RUN mkdir -p /app
WORKDIR /app
COPY butler_online/budgetbutler /app
RUN npm install
RUN npm run test --watch=false


FROM composer as build-step-php
RUN mkdir -p /api
WORKDIR /api
COPY butler_online_api/api /api
RUN composer install

# Assembly
FROM php:7-fpm-alpine
RUN docker-php-ext-install pdo mysqli pdo_mysql
RUN mkdir -p /www/api
COPY butler_online_api/site.conf /etc/nginx/conf.d/default.conf
COPY --from=build-step-angular /app/dist /www
COPY --from=build-step-php /api /www/api
COPY --from=build-step-php /api/robots.txt /www/
