# Stage 1
FROM node:18-slim as build-step-angular
RUN mkdir -p /app
WORKDIR /app
COPY butler_online/budgetbutler/package.json /app
RUN npm install
COPY butler_online/budgetbutler /app
RUN npm run build -- --configuration=production
RUN ls -la /app/dist


FROM sebastianrzk/docker-chromium-xvfb as build-step-angular-test
WORKDIR /usr/src/app
RUN apt-get update
RUN apt-get install -y gpg \
    && curl -sL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs gpg \
    && rm -rf /var/lib/apt/lists
RUN mkdir -p /app
WORKDIR /app
COPY butler_online/budgetbutler /app
RUN npm install
RUN npm run test --watch=false


FROM rust as build-step-rust
RUN mkdir -p /app
WORKDIR /app
COPY butler_online_api /app
RUN cargo build --release
RUN ls -la /app/target/release

