# Stage 1
FROM rust as build-step-rust
RUN mkdir -p /app
WORKDIR /app
COPY butler_online_api /app
RUN cargo build --release
RUN ls -la /app/target/release


# Assembly
FROM alpine
COPY --from=build-step-rust /app/target/release/budgetbutlerweb-companion-backend /
