
EINZELBUCHUNGEN_EINZELBUCHUNGEN_UEBERSICHT = '/uebersicht/'
EINZELBUCHUNGEN_DAUERAUFTRAG_UEBERSICHT = '/dauerauftraguebersicht/'
EINZELBUCHUNGEN_AUSGABE_ADD = '/addausgabe/'
EINZELBUCHUNGEN_EINNAHME_ADD = '/addeinnahme/'
EINZELBUCHUNGEN_DAUERAUFTRAG_ADD = '/adddauerauftrag/'
EINZELBUCHUNGEN_MONATSUEBERSICHT = '/monatsuebersicht/'
EINZELBUCHUNGEN_JAHRESUEBERSICHT = '/jahresuebersicht/'

GEMEINSAME_BUCHUNGEN_UEBERSICHT = '/gemeinsameuebersicht/'
GEMEINSAME_BUCHUNGEN_ADD = '/addgemeinsam/'
GEMEINSAME_BUCHUNGEN_ABRECHNEN = '/gemeinsamabrechnen/'
GEMEINSAME_BUCHUNGEN_ABRECHNUNGEN = '/uebersichtabrechnungen/'

SPAREN_SPARBUCHUNG_ADD = '/add_sparbuchung/'
SPAREN_SPARKONTO_ADD = '/add_sparkonto/'
SPAREN_DEPOTWERT_ADD = '/add_depotwert/'
SPAREN_ORDER_ADD = '/add_order/'
SPAREN_SPARBUCHUNGEN_UEBERSICHT = '/uebersicht_sparbuchungen/'
SPAREN_SPARKONTO_UEBERSICHT = '/uebersicht_sparkontos/'
SPAREN_DEPOTWERT_UEBERSICHT = '/uebersicht_depotwerte/'
SPAREN_ORDER_UEBERSICHT = '/uebersicht_order/'

CORE_CONFIGURATION = '/configuration/'
CORE_IMPORT = '/import/'
