
EINZELBUCHUNGEN_EINZELBUCHUNGEN_UEBERSICHT = '/uebersicht/'
EINZELBUCHUNGEN_DAUERAUFTRAG_UEBERSICHT = '/dauerauftraguebersicht/'
EINZELBUCHUNGEN_DAUERAUFTRAG_SPLIT = '/splitdauerauftrag/'
EINZELBUCHUNGEN_AUSGABE_ADD = '/addausgabe/'
EINZELBUCHUNGEN_EINNAHME_ADD = '/addeinnahme/'
EINZELBUCHUNGEN_DAUERAUFTRAG_ADD = '/adddauerauftrag/'
EINZELBUCHUNGEN_MONATSUEBERSICHT = '/monatsuebersicht/'
EINZELBUCHUNGEN_JAHRESUEBERSICHT = '/jahresuebersicht/'

GEMEINSAME_BUCHUNGEN_UEBERSICHT = '/gemeinsameuebersicht/'
GEMEINSAME_BUCHUNGEN_ADD = '/addgemeinsam/'
GEMEINSAME_BUCHUNGEN_ABRECHNEN = '/gemeinsamabrechnen/'
GEMEINSAME_BUCHUNGEN_ABRECHNUNGEN = '/uebersichtabrechnungen/'

SPAREN_UEBERSICHT = '/sparen/'
SPAREN_SPARBUCHUNG_ADD = '/add_sparbuchung/'
SPAREN_SPARKONTO_ADD = '/add_sparkonto/'
SPAREN_DEPOTWERT_ADD = '/add_depotwert/'
SPAREN_DEPOTAUSZUG_ADD = '/add_depotauszug/'
SPAREN_ORDER_ADD = '/add_order/'
SPAREN_ORDERDAUERAUFTRAG_ADD = '/add_orderdauerauftrag/'
SPAREN_ORDERDAUERAUFTRAG_UEBERSICHT = '/uebersicht_orderdauerauftrag/'
SPAREN_SPARBUCHUNGEN_UEBERSICHT = '/uebersicht_sparbuchungen/'
SPAREN_SPARKONTO_UEBERSICHT = '/uebersicht_sparkontos/'
SPAREN_DEPOTWERT_UEBERSICHT = '/uebersicht_depotwerte/'
SPAREN_ORDER_UEBERSICHT = '/uebersicht_order/'
SPAREN_DEPOTAUSZUEGE_UEBERSICHT = '/uebersicht_depotauszuege/'
SPAREN_UEBERSICHT_ETFS = '/uebersicht_etfs/'

CORE_CONFIGURATION = '/configuration/'
CORE_RENAME = '/rename_kategorie/'
CORE_CONFIGURATION_PARAM_SUCCESS_MESSAGE = 'success_message'
CORE_CONFIGURATION_BACKUP = '/configuration/backup/'
CORE_IMPORT = '/import/'

ONLINE_CALLBACK = '/butler-online-callback'
