version: '3'
services:
  budget-butler-static:
    image: sebastianrzk/budgetbutlerweb-companion-frontend-static
    ports:
      - "80:80"
    restart: unless-stopped
  budget-butler-api:
    image: sebastianrzk/budgetbutlerweb-companion-api
    env_file:
      - api.env
    restart: unless-stopped
    networks:
      - butler-internal
      - butler-db
  budget-butler-cron:
    image: sebastianrzk/budgetbutlerweb-companion-cron
    env_file:
      - api.env
    restart: unless-stopped
    networks:
      - butler-db
  db:
    image: mariadb
    volumes:
      - db:/var/lib/mysql
    env_file:
      - db.env
    command: --max_allowed_packet=134217728
    restart: unless-stopped
    networks:
      - butler-db

volumes:
  db:
networks:
  butler-internal:
  butler-db:
