version: '3'
services:
  budget-butler-static:
    image: sebastianrzk/budgetbutlerweb-companion-static
    ports:
      - "80:80"
    restart: unless-stopped
  budget-butler-api:
    image: sebastianrzk/budgetbutlerweb-companion-api
    env_file:
      - api.env
    restart: unless-stopped

  db:
    image: mariadb
    volumes:
      - db:/var/lib/mysql
    env_file:
      - db.env
    restart: unless-stopped


volumes:
  db:

