version: '3'
services:
  budget-butler-static:
    image: sebastianrzk/budgetbutlerweb-companion-static
    ports:
      - "80:80"
    env_file:
      - db.env
    restart: unless-stopped
  budget-butler-fpm:
    image: sebastianrzk/budgetbutlerweb-companion-fpm
    env_file:
      - db.env
    restart: unless-stopped

  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - db.env
    restart: unless-stopped


volumes:
  db:

