title: BudgetButlerWeb
description: Einfaches und flottes Haushaltsbuch mit Offline- und Online-Funktionalität
show_downloads: true
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
  - jemoji
markdown: kramdown