name: Build Offline Application and Companion App

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  butler-offline-test:
    name: offline cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test
        working-directory: ./butler_offline
  butler-offline-assembly:
    name: offline assembly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: bash build.sh
        working-directory: .
  butler-offline-formatting:
    name: offline cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name:  Check
        run: cargo fmt --all -- --check
        working-directory: ./butler_offline
  butler-offline-application-wrapper:
    name: offline application-wrapper build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install and npm run CI commands
        run: |
          npm i
          npm run publish
        working-directory: ./application-wrapper/BudgetButlerWeb
  butler-offline-application-wrapper-lint:
    name: offline application-wrapper lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install and npm run CI commands
        run: |
          npm i
          npm run lint
        working-directory: ./application-wrapper/BudgetButlerWeb
  butler_online_frontend:
    name: online api frontend test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: execute tests
        run: |
          docker build -f Dockerfile.test .
  butker_online_frontend_lint:
    name: online api frontend lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install and npm run CI commands
        run: |
          npm i
          npm run lint
        working-directory: ./butler_online/budgetbutler
  butler_online_api:
    name: online api build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: execute tests
        run: |
          docker build -f Dockerfile.api .
  butler_online_api_formatting:
    name: online api cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Check
        run: cargo fmt --all -- --check
        working-directory: ./butler_online_api
  butler_online_cron:
    name: online api cron build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: execute tests
        run: |
          docker build -f Dockerfile.cron .
