# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Python application

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        #PATH: $PATH:$PWD/geckodriver
        TRAVIS_INTEGRATION: TRUE
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sh ./ci/install_requirements.sh
        pip install flake8 pytest
        wget https://github.com/mozilla/geckodriver/releases/download/v0.32.0/geckodriver-v0.32.0-linux64.tar.gz
        mkdir geckodriver
        tar -xzf geckodriver-v0.32.0-linux64.tar.gz -C geckodriver
        wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh
        source ~/.nvm/nvm.sh
        nvm install 12
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Unit test with pytest
      run: |
        sh ci/run_unit_tests.sh
    - name: Integration test with pytest
      run: |
        sh ci/run_integration_tests.sh
  docker:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: execute tests
        run: |
          docker build -f Dockerfile.test .

