name: Publish Companion App to DockerHub

on:
  push:
    tags:
      - "v*.*.*"
    branches: [ test-image-push ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push static
        id: docker_build_bb_static
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.static
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/budgetbutlerweb-companion-frontend-static:latest
      -
        name: Build and push api
        id: docker_build_bb_api
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile.api
          platforms: linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/budgetbutlerweb-companion-api:latest
      -
        name: Build and push cron
        id: docker_build_bb_cron
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile.cron
          platforms: linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/budgetbutlerweb-companion-cron:latest
      -
        name: Build and push desktop app
        id: docker_build_bb_desktopapp
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile.desktopapp
          platforms: linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/budgetbutlerweb-desktopapp:latest
      -
        name: Build and push desktop app arm64
        id: docker_build_bb_desktopapp-arm64
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile.desktopapp
          platforms: linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/budgetbutlerweb-desktopapp:latest-arm64
